In [21]:
from __future__ import print_function
import torch
import numpy as np

pytorch 튜토리얼

https://pytorch.org/docs/stable/torch.html

선형대수

https://pytorch.org/docs/stable/torch.html

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

1. NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우

2. 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

# 1. tensor 

### 1) 생성

In [29]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [13]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6653, 0.3830, 0.7299],
        [0.6450, 0.4915, 0.7562],
        [0.0911, 0.6212, 0.7958],
        [0.0875, 0.5972, 0.9710],
        [0.7178, 0.0718, 0.7677]])


In [14]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [15]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [16]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [17]:
print(x.size())

torch.Size([5, 3])


### 2) numpy

In [23]:
a = np.array([1,2,3])
t = torch.from_numpy(a)
print(t)
print(t[0])

tensor([1, 2, 3], dtype=torch.int32)
tensor(1, dtype=torch.int32)


# 2. 연산 

In [9]:
x = torch.tensor([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12],
                [13,14,15]], dtype=torch.double)
y = torch.rand(5, 3, dtype=torch.double)

In [3]:
y

tensor([[0.9190, 0.1469, 0.9655],
        [0.4652, 0.2339, 0.1957],
        [0.6520, 0.5024, 0.1912],
        [0.8708, 0.5200, 0.3473],
        [0.7681, 0.1397, 0.5740]], dtype=torch.float64)

### 1) 더하기

In [40]:
x+y

tensor([[ 1.8273,  2.9065,  3.6880],
        [ 4.4223,  5.1514,  6.2587],
        [ 7.8577,  8.8550,  9.1731],
        [10.0372, 11.4372, 12.8024],
        [13.1836, 14.3191, 15.2016]], dtype=torch.float64)

In [27]:
torch.add(x,y)

tensor([[0.6441, 0.2114, 1.7807],
        [1.7362, 0.5475, 0.9764],
        [0.9321, 1.6054, 1.4457],
        [1.0231, 1.0634, 0.8545],
        [0.7943, 1.6903, 1.9665]], dtype=torch.float64)

In [7]:
result = torch.empty(5, 3, dtype=torch.double)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1999,  2.3471,  3.5142],
        [ 4.0979,  5.9300,  6.7619],
        [ 7.1409,  8.9211,  9.6617],
        [10.1190, 11.1000, 12.5938],
        [13.9776, 14.9555, 15.1672]], dtype=torch.float64)


### 2) 복사

In [10]:
y.copy_(x)
y

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]], dtype=torch.float64)

### 3) transform

In [11]:
x.t_()
x

tensor([[ 1.,  4.,  7., 10., 13.],
        [ 2.,  5.,  8., 11., 14.],
        [ 3.,  6.,  9., 12., 15.]], dtype=torch.float64)

### 4) 인덱싱 

In [15]:
x[:, 1] # 모든행, 1열

tensor([4., 5., 6.], dtype=torch.float64)

### 5) size, shape 변경

In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # 사이즈가 -1인 경우 다른 차원들을 사용하여 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
print(x)
print(y)
print(z)

tensor([[ 0.3241, -0.7442, -0.3130,  1.0924],
        [ 0.5857, -1.4931,  2.3960,  1.5307],
        [ 1.0557,  0.1920,  0.7144, -0.3095],
        [-0.7603,  0.8234,  1.2534, -1.3112]])
tensor([ 0.3241, -0.7442, -0.3130,  1.0924,  0.5857, -1.4931,  2.3960,  1.5307,
         1.0557,  0.1920,  0.7144, -0.3095, -0.7603,  0.8234,  1.2534, -1.3112])
tensor([[ 0.3241, -0.7442, -0.3130,  1.0924,  0.5857, -1.4931,  2.3960,  1.5307],
        [ 1.0557,  0.1920,  0.7144, -0.3095, -0.7603,  0.8234,  1.2534, -1.3112]])


### 6) .item()

tensor에 값이 하나만 있다면 값을 얻을 수 있다.

In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1948])
0.19475093483924866


In [40]:
x+y

tensor([[ 1.8273,  2.9065,  3.6880],
        [ 4.4223,  5.1514,  6.2587],
        [ 7.8577,  8.8550,  9.1731],
        [10.0372, 11.4372, 12.8024],
        [13.1836, 14.3191, 15.2016]], dtype=torch.float64)

In [27]:
torch.add(x,y)

tensor([[0.6441, 0.2114, 1.7807],
        [1.7362, 0.5475, 0.9764],
        [0.9321, 1.6054, 1.4457],
        [1.0231, 1.0634, 0.8545],
        [0.7943, 1.6903, 1.9665]], dtype=torch.float64)

In [7]:
result = torch.empty(5, 3, dtype=torch.double)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1999,  2.3471,  3.5142],
        [ 4.0979,  5.9300,  6.7619],
        [ 7.1409,  8.9211,  9.6617],
        [10.1190, 11.1000, 12.5938],
        [13.9776, 14.9555, 15.1672]], dtype=torch.float64)


### 2) 복사

In [10]:
y.copy_(x)
y

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]], dtype=torch.float64)

### 3) transform

In [11]:
x.t_()
x

tensor([[ 1.,  4.,  7., 10., 13.],
        [ 2.,  5.,  8., 11., 14.],
        [ 3.,  6.,  9., 12., 15.]], dtype=torch.float64)

### 4) 인덱싱 

In [15]:
x[:, 1] # 모든행, 1열

tensor([4., 5., 6.], dtype=torch.float64)

### 5) size, shape 변경

In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # 사이즈가 -1인 경우 다른 차원들을 사용하여 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
print(x)
print(y)
print(z)

tensor([[ 0.3241, -0.7442, -0.3130,  1.0924],
        [ 0.5857, -1.4931,  2.3960,  1.5307],
        [ 1.0557,  0.1920,  0.7144, -0.3095],
        [-0.7603,  0.8234,  1.2534, -1.3112]])
tensor([ 0.3241, -0.7442, -0.3130,  1.0924,  0.5857, -1.4931,  2.3960,  1.5307,
         1.0557,  0.1920,  0.7144, -0.3095, -0.7603,  0.8234,  1.2534, -1.3112])
tensor([[ 0.3241, -0.7442, -0.3130,  1.0924,  0.5857, -1.4931,  2.3960,  1.5307],
        [ 1.0557,  0.1920,  0.7144, -0.3095, -0.7603,  0.8234,  1.2534, -1.3112]])


### 6) .item()

tensor에 값이 하나만 있다면 값을 얻을 수 있다.

In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1948])
0.19475093483924866
