In [1]:
from __future__ import print_function
import torch

# 연산, 선형대수

In [3]:
x = torch.tensor([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12],
                [13,14,15]], dtype=torch.double)
y = torch.tensor([[2,3,4],
                [5,6,7],
                [8,9,10],
                [11,12,13],
                [14,15,16]], dtype=torch.double)

### 1) 더하기

In [4]:
x+y

tensor([[ 3.,  5.,  7.],
        [ 9., 11., 13.],
        [15., 17., 19.],
        [21., 23., 25.],
        [27., 29., 31.]], dtype=torch.float64)

In [5]:
torch.add(x,y)

tensor([[ 3.,  5.,  7.],
        [ 9., 11., 13.],
        [15., 17., 19.],
        [21., 23., 25.],
        [27., 29., 31.]], dtype=torch.float64)

In [6]:
result = torch.empty(5, 3, dtype=torch.double)
torch.add(x, y, out=result)
print(result)

tensor([[ 3.,  5.,  7.],
        [ 9., 11., 13.],
        [15., 17., 19.],
        [21., 23., 25.],
        [27., 29., 31.]], dtype=torch.float64)


### 2) 복사

In [7]:
y.copy_(x)
y

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]], dtype=torch.float64)

### 3) transform

In [8]:
x.t_()
x

tensor([[ 1.,  4.,  7., 10., 13.],
        [ 2.,  5.,  8., 11., 14.],
        [ 3.,  6.,  9., 12., 15.]], dtype=torch.float64)

### 4) 인덱싱 

In [9]:
x[:, 1] # 모든행, 1열

tensor([4., 5., 6.], dtype=torch.float64)

### 5) size, shape 변경

In [10]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # 사이즈가 -1인 경우 다른 차원들을 사용하여 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [11]:
print(x)
print(y)
print(z)

tensor([[ 1.2791, -1.2440, -0.0942,  1.2800],
        [-0.2087,  1.2388, -1.4500, -1.1243],
        [-1.0701,  0.4547,  0.5237,  0.3490],
        [ 0.1835,  1.6897, -1.6305, -1.0681]])
tensor([ 1.2791, -1.2440, -0.0942,  1.2800, -0.2087,  1.2388, -1.4500, -1.1243,
        -1.0701,  0.4547,  0.5237,  0.3490,  0.1835,  1.6897, -1.6305, -1.0681])
tensor([[ 1.2791, -1.2440, -0.0942,  1.2800, -0.2087,  1.2388, -1.4500, -1.1243],
        [-1.0701,  0.4547,  0.5237,  0.3490,  0.1835,  1.6897, -1.6305, -1.0681]])


### 6) .item()

tensor에 값이 하나만 있다면 값을 얻을 수 있다.

In [12]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5142])
0.5141617655754089
